// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcYQCrCT21ex7mhdtmOR2W4f6XW9WkMzc',
    appId: '1:781029568611:web:5e1773cc50292423c2c856',
    messagingSenderId: '781029568611',
    projectId: 'company-47f7c',
    authDomain: 'company-47f7c.firebaseapp.com',
    databaseURL: 'https://company-47f7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-47f7c.appspot.com',
    measurementId: 'G-175SREJ86P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTY8M8kbR2mkiiByBDbfUVA2ZBDR90CSk',
    appId: '1:781029568611:android:750cf36abce5a125c2c856',
    messagingSenderId: '781029568611',
    projectId: 'company-47f7c',
    databaseURL: 'https://company-47f7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-47f7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ee3TiDeFRWWZRP0548SwYYqSVTxd4Fk',
    appId: '1:781029568611:ios:33eeff0db737ee6dc2c856',
    messagingSenderId: '781029568611',
    projectId: 'company-47f7c',
    databaseURL: 'https://company-47f7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-47f7c.appspot.com',
    iosBundleId: 'com.example.utsKivenkeita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ee3TiDeFRWWZRP0548SwYYqSVTxd4Fk',
    appId: '1:781029568611:ios:33eeff0db737ee6dc2c856',
    messagingSenderId: '781029568611',
    projectId: 'company-47f7c',
    databaseURL: 'https://company-47f7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-47f7c.appspot.com',
    iosBundleId: 'com.example.utsKivenkeita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcYQCrCT21ex7mhdtmOR2W4f6XW9WkMzc',
    appId: '1:781029568611:web:cdaa3d88582c6085c2c856',
    messagingSenderId: '781029568611',
    projectId: 'company-47f7c',
    authDomain: 'company-47f7c.firebaseapp.com',
    databaseURL: 'https://company-47f7c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-47f7c.appspot.com',
    measurementId: 'G-57ZNWLN1SX',
  );
}
